@api_HostAddress = http://localhost:5170

###

POST {{api_HostAddress}}/auth/register
Content-Type: application/json

{
  "email": "john@example.com",
  "username": "john",
  "password": "password123"
}

###

POST {{api_HostAddress}}/auth/login
Content-Type: application/json

{
  "email": "john@example.com",
  "password": "password123"
}

###

GET {{api_HostAddress}}/user/{{$guid}}
Content-Type: application/json

###

GET {{api_HostAddress}}/user/{{$guid}}/memberships

###

GET {{api_HostAddress}}/user/{{$guid}}/memberships/{{$guid}}

###